/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useCallback, useState } from "react";
import * as THREE from "three";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import characterModel from "../assets/3d/Soldier.glb";

export default function Character(props) {
  const group = useRef();
  const { camera } = useThree();
  const { scene, nodes, materials, animations } = useGLTF(characterModel);
  const { actions } = useAnimations(animations, group);
  const [isRunning, setIsRunning] = useState(false);
  const [direction, setDirection] = useState(null);
  const [velocity, setVelocity] = useState(0);
  const DEFAULT_VELOCITY = 3;

  const handleKeyDown = useCallback(
    (event) => {
      if (!isRunning) {
        switch (event.key) {
          case "w":
            setDirection("north");
            break;
          case "a":
            setDirection("west");
            break;
          case "s":
            setDirection("south");
            break;
          case "d":
            setDirection("east");
            break;
          default:
            return; // Ignore other keys
        }
        actions["Idle"].reset().fadeOut(0.2);
        actions["Run"].reset().fadeIn(0.2).play();
        setIsRunning(true);
        setVelocity(DEFAULT_VELOCITY);
      }
    },
    [isRunning, actions, DEFAULT_VELOCITY]
  );

  useFrame((state, delta) => {
    if (group.current && direction && velocity > 0) {
      let directionVector;
      switch (direction) {
        case "north":
          directionVector = new THREE.Vector3(0, 0, -1);
          break;
        case "west":
          directionVector = new THREE.Vector3(-1, 0, 0);
          break;
        case "south":
          directionVector = new THREE.Vector3(0, 0, 1);
          break;
        case "east":
          directionVector = new THREE.Vector3(1, 0, 0);
          break;
        default:
          directionVector = new THREE.Vector3();
          break;
      }
      directionVector.multiplyScalar(velocity * delta);
      group.current.position.add(directionVector);

      const x = group.current.position.x;
      const z = group.current.position.z;
      camera.position.set(x, camera.position.y, z + 5); // Adjust '5' to set how far behind you want the camera
      camera.lookAt(group.current.position); // Ensure the camera always points at the character
    }
  });

  const handleKeyUp = useCallback(
    (event) => {
      if (["w", "a", "s", "d"].includes(event.key) && isRunning) {
        actions["Run"].fadeOut(0.2);
        actions["Idle"].reset().fadeIn(0.2).play();
        setIsRunning(false);
        setVelocity(0);
        setDirection(null);
      }
    },
    [isRunning, actions]
  );

  useEffect(() => {
    window.addEventListener("keydown", handleKeyDown);
    window.addEventListener("keyup", handleKeyUp);

    return () => {
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
    };
  }, [handleKeyDown, handleKeyUp]);

  useEffect(() => {
    actions["Idle"].play();
  }, [actions]);

  useEffect(() => {
    if (direction && group.current) {
      switch (direction) {
        case "north":
          group.current.rotation.set(0, Math.PI, 0);
          break;
        case "west":
          group.current.rotation.set(0, -Math.PI / 2, 0);
          break;
        case "south":
          group.current.rotation.set(0, 0, 0);
          break;
        case "east":
          group.current.rotation.set(0, Math.PI / 2, 0);
          break;
        default:
          break;
      }
    }
  }, [direction]);

  useEffect(() => {
    if (velocity > 0) {
    }
  }, [velocity]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          castShadow
          name="Character"
          position={[0, 0, 0]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={0.005}
        >
          <skinnedMesh
            name="vanguard_Mesh"
            geometry={nodes.vanguard_Mesh.geometry}
            material={materials.VanguardBodyMat}
            skeleton={nodes.vanguard_Mesh.skeleton}
          />
          <skinnedMesh
            name="vanguard_visor"
            geometry={nodes.vanguard_visor.geometry}
            material={materials.Vanguard_VisorMat}
            skeleton={nodes.vanguard_visor.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
}
