/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useCallback, useState } from "react";
import * as THREE from "three";
import { Box3, Box3Helper, Mesh, BoxGeometry } from "three";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame, useThree, extend } from "@react-three/fiber";

import characterModel from "../assets/3d/Soldier.glb";

extend({ Box3Helper });

export default function Character(props) {
  const group = useRef();
  const boxRef = useRef();
  const { camera, scene } = useThree();
  const {
    scene: gltfScene,
    nodes,
    materials,
    animations,
  } = useGLTF(characterModel);
  const { actions } = useAnimations(animations, group);
  const [isRunning, setIsRunning] = useState(false);
  const [direction, setDirection] = useState(null);
  const [velocity, setVelocity] = useState(0);
  const [objectBoxes, setObjectBoxes] = useState([]);
  const DEFAULT_VELOCITY = 3;

  useEffect(() => {
    const foundBoxObjects = [];
    if (objectBoxes.length === 0) {
      scene.traverse((object) => {
        if (object instanceof Mesh && object.geometry instanceof BoxGeometry) {
          const objectBox = new Box3().setFromObject(object);
          foundBoxObjects.push(objectBox);
        }
      });

      setObjectBoxes(foundBoxObjects);
    }
  }, []);

  const resetCamera = () => {
    const x = group.current.position.x;
    const z = group.current.position.z;
    camera.position.set(x, camera.position.y, z + 5);
    camera.lookAt(group.current.position);
  };

  useEffect(() => {
    if (group.current) {
      resetCamera();

      const box = new Box3().setFromObject(group.current);
      const helper = new Box3Helper(box, 0xffff00);
      boxRef.current = helper;

      return () => {
        scene.remove(helper);
      };
    }
  }, [group, scene]);

  useEffect(() => {
    actions["Idle"].play();
  }, [actions]);

  const handleKeyDown = useCallback(
    (event) => {
      if (!isRunning) {
        switch (event.key) {
          case "w":
            setDirection("north");
            break;
          case "a":
            setDirection("west");
            break;
          case "s":
            setDirection("south");
            break;
          case "d":
            setDirection("east");
            break;
          default:
            return; // Ignore other keys
        }
        actions["Idle"].reset().fadeOut(0.2);
        actions["Run"].reset().fadeIn(0.2).play();
        setIsRunning(true);
        setVelocity(DEFAULT_VELOCITY);
      }
    },
    [isRunning, actions, DEFAULT_VELOCITY]
  );

  const collisionDetector = () => {
    if (objectBoxes.length > 0) {
      objectBoxes.forEach((objectBox) => {
        const characterBox = new Box3().setFromObject(group.current);
        if (characterBox.intersectsBox(objectBox)) {
          setVelocity(0);
        }
      });
    }
  };

  useFrame((_, delta) => {
    if (group.current && direction && velocity > 0) {
      let directionVector;
      switch (direction) {
        case "north":
          directionVector = new THREE.Vector3(0, 0, -1);
          break;
        case "west":
          directionVector = new THREE.Vector3(-1, 0, 0);
          break;
        case "south":
          directionVector = new THREE.Vector3(0, 0, 1);
          break;
        case "east":
          directionVector = new THREE.Vector3(1, 0, 0);
          break;
        default:
          break;
      }
      directionVector.multiplyScalar(velocity * delta);
      group.current.position.add(directionVector);
      // Update the bounding box position
      boxRef.current.box.setFromObject(group.current);

      resetCamera();

      collisionDetector();
    }
  });

  const handleKeyUp = useCallback(
    (event) => {
      if (["w", "a", "s", "d"].includes(event.key) && isRunning) {
        actions["Run"].fadeOut(0.2);
        actions["Idle"].reset().fadeIn(0.2).play();
        setIsRunning(false);
        setVelocity(0);
        setDirection(null);
      }
    },
    [isRunning, actions]
  );

  useEffect(() => {
    window.addEventListener("keydown", handleKeyDown);
    window.addEventListener("keyup", handleKeyUp);

    return () => {
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
    };
  }, [handleKeyDown, handleKeyUp]);

  useEffect(() => {
    if (direction && group.current) {
      switch (direction) {
        case "north":
          group.current.rotation.set(0, Math.PI, 0);
          break;
        case "west":
          group.current.rotation.set(0, -Math.PI / 2, 0);
          break;
        case "south":
          group.current.rotation.set(0, 0, 0);
          break;
        case "east":
          group.current.rotation.set(0, Math.PI / 2, 0);
          break;
        default:
          break;
      }
    }
  }, [direction]);

  return (
    <group ref={group} {...props} position={[0, 0, 7]} dispose={null}>
      <group name="Scene">
        <group
          castShadow
          name="Character"
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={0.003}
        >
          <skinnedMesh
            name="vanguard_Mesh"
            geometry={nodes.vanguard_Mesh.geometry}
            material={materials.VanguardBodyMat}
            skeleton={nodes.vanguard_Mesh.skeleton}
          />
          <skinnedMesh
            name="vanguard_visor"
            geometry={nodes.vanguard_visor.geometry}
            material={materials.Vanguard_VisorMat}
            skeleton={nodes.vanguard_visor.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
}
