/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useCallback, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import characterModel from "../assets/3d/Soldier.glb";

export default function Character(props) {
  const group = useRef();
  const { scene, nodes, materials, animations } = useGLTF(characterModel);
  const { actions } = useAnimations(animations, group);
  const [isRunning, setIsRunning] = useState(false);
  const [direction, setDirection] = useState(null);

  const handleKeyDown = useCallback(
    (event) => {
      if (!isRunning) {
        switch (event.key) {
          case "w":
            setDirection("north");
            break;
          case "a":
            setDirection("west");
            break;
          case "s":
            setDirection("south");
            break;
          case "d":
            setDirection("east");
            break;
          default:
            return; // Ignore other keys
        }
        actions["Idle"].reset().fadeOut(0.2);
        actions["Run"].reset().fadeIn(0.2).play();
        setIsRunning(true);
      }
    },
    [isRunning, actions]
  );

  const handleKeyUp = useCallback(
    (event) => {
      if (["w", "a", "s", "d"].includes(event.key) && isRunning) {
        actions["Run"].fadeOut(0.2);
        actions["Idle"].reset().fadeIn(0.2).play();
        setIsRunning(false);
        setDirection(null);
      }
    },
    [isRunning, actions]
  );

  useEffect(() => {
    window.addEventListener("keydown", handleKeyDown);
    window.addEventListener("keyup", handleKeyUp);

    return () => {
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
    };
  }, [handleKeyDown, handleKeyUp]);

  useEffect(() => {
    actions["Idle"].play();
  }, [actions]);

  useEffect(() => {
    if (direction && group.current) {
      switch (direction) {
        case "north":
          group.current.rotation.set(0, Math.PI, 0);
          break;
        case "west":
          group.current.rotation.set(0, -Math.PI / 2, 0);
          break;
        case "south":
          group.current.rotation.set(0, 0, 0);
          break;
        case "east":
          group.current.rotation.set(0, Math.PI / 2, 0);
          break;
        default:
          break;
      }
    }
  }, [direction]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          castShadow
          name="Character"
          position={[0, 0, 0]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={0.01}
        >
          <skinnedMesh
            name="vanguard_Mesh"
            geometry={nodes.vanguard_Mesh.geometry}
            material={materials.VanguardBodyMat}
            skeleton={nodes.vanguard_Mesh.skeleton}
          />
          <skinnedMesh
            name="vanguard_visor"
            geometry={nodes.vanguard_visor.geometry}
            material={materials.Vanguard_VisorMat}
            skeleton={nodes.vanguard_visor.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
}
