/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { Box3, Box3Helper } from "three";
import { useFrame, useThree, extend } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

import cityScene from "../assets/3d/lowpolycity.glb";

extend({ Box3Helper });

export default function City(props) {
  const { scene } = useThree();
  const { nodes, materials } = useGLTF(cityScene);
  const cityRef = useRef();

  return (
    <group
      ref={cityRef}
      rotation={[0, Math.PI / 2, 0]}
      scale={0.25}
      {...props}
      dispose={null}
    >
      <group position={[0, 0, -17]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019.geometry}
          material={materials["concrete blocks"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_1.geometry}
          material={materials["grass blocks"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_2.geometry}
          material={materials["concrete sidewalks"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_3.geometry}
          material={materials.sand}
        />
        <group position={[2.73, 0.299, 2.793]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013.geometry}
            material={materials[" barrels orange"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_1.geometry}
            material={materials["Metal building light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_2.geometry}
            material={materials["Metal building"]}
          />
        </group>
        <group position={[-1.821, 2.28, 3.551]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube014.geometry}
            material={materials[" barrels orange"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube014_1.geometry}
            material={materials["Metal building light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube014_2.geometry}
            material={materials["Metal building"]}
          />
        </group>
        <group position={[-4.239, 0.299, 3.633]} rotation={[0, -0.544, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015.geometry}
            material={materials[" barrels orange"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_1.geometry}
            material={materials["Metal building light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_2.geometry}
            material={materials["Metal building"]}
          />
        </group>
        <group
          position={[-3.82, 0.299, 4.071]}
          rotation={[-Math.PI, 1.258, -Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016.geometry}
            material={materials[" barrels orange"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016_1.geometry}
            material={materials["Metal building light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016_2.geometry}
            material={materials["Metal building"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.builidng_structure.geometry}
          material={materials["Metal building"]}
          position={[0.056, -0.039, -0.006]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.construction__dumpster.geometry}
          material={materials[" barrels orange"]}
          position={[-3.899, 0.287, -2.925]}
        />
      </group>
      <group position={[0, 0, -0.327]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube039.geometry}
          material={materials["concrete blocks"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube039_1.geometry}
          material={materials["grass blocks"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube039_2.geometry}
          material={materials["concrete sidewalks"]}
        />
        <group position={[-0.051, 0.271, 0.217]} rotation={[0, -1.571, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube038.geometry}
            material={materials["main material - random color"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube038_1.geometry}
            material={materials["glass windows"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube038_2.geometry}
            material={materials["blk absolut"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube038_3.geometry}
            material={materials["Metal building light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube038_4.geometry}
            material={materials["Metal building"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube038_5.geometry}
            material={materials["Metal panel"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube038_6.geometry}
            material={materials["Lights-Pole"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube038_7.geometry}
            material={materials["light - red"]}
          />
        </group>
      </group>
      <group position={[-16.647, 0, -17.493]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube036.geometry}
          material={materials["concrete blocks"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube036_1.geometry}
          material={materials["grass blocks"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube036_2.geometry}
          material={materials["concrete sidewalks"]}
        />
        <group position={[-0.224, 0.301, 0.01]} rotation={[0, 1.571, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube037.geometry}
            material={materials["main material - random color"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube037_1.geometry}
            material={materials["glass windows"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube037_2.geometry}
            material={materials["Metal building light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube037_3.geometry}
            material={materials["Metal building"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube037_4.geometry}
            material={materials["Metal panel"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube037_5.geometry}
            material={materials["blk absolut"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube037_6.geometry}
            material={materials["main material - random color"]}
          />
        </group>
      </group>
      <group position={[-0.09, 0.197, 17.069]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034.geometry}
          material={materials["concrete blocks"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034_1.geometry}
          material={materials["grass blocks"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034_2.geometry}
          material={materials["concrete sidewalks"]}
        />
        <group
          position={[0.014, 0.107, -0.124]}
          rotation={[0.016, -Math.PI / 2, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube035.geometry}
            material={materials["main material - random color"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube035_1.geometry}
            material={materials["glass windows"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube035_2.geometry}
            material={materials["glass windows"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube035_3.geometry}
            material={materials["Metal building light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube035_4.geometry}
            material={materials["Metal building"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube035_5.geometry}
            material={materials["Metal panel"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube035_6.geometry}
            material={materials["blk absolut"]}
          />
        </group>
      </group>
      <group position={[-17.09, 0.171, 17.022]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials["concrete blocks"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials["grass blocks"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials["concrete sidewalks"]}
        />
        <group position={[-2.174, 0.087, -1.771]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001.geometry}
            material={materials["balloon red"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials["balloon brown"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_2.geometry}
            material={materials["rope brown"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass.geometry}
          material={materials["grass prop"]}
          position={[0.414, 0.099, -4.097]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass2.geometry}
          material={materials["grass prop"]}
          position={[0.405, 0.098, -3.438]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass3.geometry}
          material={materials["grass prop"]}
          position={[0.407, 0.099, -3.755]}
        />
        <group position={[0.826, 0.084, -3.35]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle.geometry}
            material={materials["Metal building"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_1.geometry}
            material={materials["Lights-Pole"]}
          />
        </group>
        <group position={[0.784, 0.09, -3.958]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle003.geometry}
            material={materials["metal very light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle003_1.geometry}
            material={materials.metal}
          />
        </group>
        <group position={[0.875, 0.092, 1.859]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007.geometry}
            material={materials["tree trunk"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007_1.geometry}
            material={materials["tree foliage"]}
          />
        </group>
        <group position={[0.881, 0.092, 3.756]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004.geometry}
            material={materials["tree trunk"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004_1.geometry}
            material={materials["tree foliage"]}
          />
        </group>
        <group position={[0.991, 0.09, 0.299]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003.geometry}
            material={materials["tree trunk"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003_1.geometry}
            material={materials["tree foliage"]}
          />
        </group>
        <group position={[0.942, 0.092, -1.684]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={materials["tree trunk"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={materials["tree foliage"]}
          />
        </group>
      </group>
      <group position={[-17.09, 0.171, 0.022]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024.geometry}
          material={materials["concrete blocks"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_1.geometry}
          material={materials["grass blocks"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_2.geometry}
          material={materials["concrete sidewalks"]}
        />
        <group
          position={[-3.331, 0.099, 2.219]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_5.geometry}
            material={materials["car color - random"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_5_1.geometry}
            material={materials["glass windows"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_5_2.geometry}
            material={materials["Lights-Pole"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_5_3.geometry}
            material={materials["Metal building light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_5_4.geometry}
            material={materials.tires}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_5_5.geometry}
            material={materials["metal very light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_5_6.geometry}
            material={materials["blk absolut"]}
          />
        </group>
        <group position={[1.098, 0.099, 2.219]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_7.geometry}
            material={materials["car color - random"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_7_1.geometry}
            material={materials["glass windows"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_7_2.geometry}
            material={materials["Lights-Pole"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_7_3.geometry}
            material={materials["Metal building light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_7_4.geometry}
            material={materials.tires}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_7_5.geometry}
            material={materials["metal very light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_7_6.geometry}
            material={materials["blk absolut"]}
          />
        </group>
        <group position={[-1.066, 0.099, 2.219]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_6.geometry}
            material={materials["car color - random"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_6_1.geometry}
            material={materials["glass windows"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_6_2.geometry}
            material={materials["Lights-Pole"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_6_3.geometry}
            material={materials["Metal building light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_6_4.geometry}
            material={materials.tires}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_6_5.geometry}
            material={materials["metal very light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car_6_6.geometry}
            material={materials["blk absolut"]}
          />
        </group>
        <group position={[0.423, 0.118, -2.913]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025.geometry}
            material={materials["main material - random color"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_1.geometry}
            material={materials["glass transparent"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_2.geometry}
            material={materials["concrete blocks"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_3.geometry}
            material={materials["main material - random color"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_4.geometry}
            material={materials["Metal panel"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_5.geometry}
            material={materials["glass windows"]}
          />
        </group>
      </group>
      <group position={[17, 0, 0.327]} rotation={[0, -1.571, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028.geometry}
          material={materials["concrete blocks"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_1.geometry}
          material={materials["grass blocks"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_2.geometry}
          material={materials["concrete sidewalks"]}
        />
        <group position={[0.782, 0.26, -3.366]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01002.geometry}
            material={materials["car color - random"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01002_1.geometry}
            material={materials["glass windows"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01002_2.geometry}
            material={materials["Lights-Pole"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01002_3.geometry}
            material={materials["Metal building light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01002_4.geometry}
            material={materials.tires}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01002_5.geometry}
            material={materials["metal  ultra light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01002_6.geometry}
            material={materials[" barrels orange"]}
          />
        </group>
        <group position={[-0.792, 0.26, -3.366]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01003.geometry}
            material={materials["car color - random"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01003_1.geometry}
            material={materials["glass windows"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01003_2.geometry}
            material={materials["Lights-Pole"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01003_3.geometry}
            material={materials["Metal building light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01003_4.geometry}
            material={materials.tires}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01003_5.geometry}
            material={materials["metal  ultra light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01003_6.geometry}
            material={materials["blk absolut"]}
          />
        </group>
        <group position={[2.378, 0.26, -3.366]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01001.geometry}
            material={materials["car color - random"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01001_1.geometry}
            material={materials["glass windows"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01001_2.geometry}
            material={materials["Lights-Pole"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01001_3.geometry}
            material={materials["Metal building light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01001_4.geometry}
            material={materials.tires}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01001_5.geometry}
            material={materials["metal  ultra light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01001_6.geometry}
            material={materials["blk absolut"]}
          />
        </group>
        <group
          position={[-2.375, 0.26, -3.366]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01.geometry}
            material={materials["car color - random"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01_1.geometry}
            material={materials["glass windows"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01_2.geometry}
            material={materials["Lights-Pole"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01_3.geometry}
            material={materials["Metal building light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01_4.geometry}
            material={materials.tires}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01_5.geometry}
            material={materials["metal  ultra light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.car01_6.geometry}
            material={materials["blk absolut"]}
          />
        </group>
        <group position={[0.882, 0.27, 1.111]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube029.geometry}
            material={materials["main material - random color"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube029_1.geometry}
            material={materials["glass windows"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube029_2.geometry}
            material={materials["Metal building light"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube029_3.geometry}
            material={materials["Metal building"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube029_4.geometry}
            material={materials["blk absolut"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube029_5.geometry}
            material={materials["Lights-Pole"]}
          />
        </group>
      </group>
    </group>
  );
}
