/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";

import houseScene from "../assets/3d/house.glb";

export default function House(props) {
  const { scene, nodes, materials } = useGLTF(houseScene);
  const houseRef = useRef();

  useEffect(() => {
    if (houseRef.current) {
      houseRef.current.rotation.set(0, Math.PI / 6, -Math.PI / 20);
    }
  }, [scene]);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={houseRef}
        castShadow
        receiveShadow
        geometry={nodes.house_003.geometry}
        material={materials.Material}
      />
    </group>
  );
}
