/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import roadModel from "../assets/3d/roadkit.glb";

export default function Road(props) {
  const { nodes, materials } = useGLTF(roadModel);

  return (
    <group {...props} dispose={null} scale={0.6}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["road_side-Mesh"].geometry}
        material={materials["pavement.022"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["road_side-Mesh_1"].geometry}
        material={materials["asphalt.010"]}
      />
    </group>
  );
}
